### PR TITLE
Power support

### PR DESCRIPTION
**Pull request by user959**
Adding Power support for hyperscan analogous to #212. The work was done under @danlark1 guidance.

Unit tests were run on the Power9 server.

### CODE REVIEW

**Comment by hulksmaaash** [comment]
@user959 you may want to consider adding support to https://github.com/VectorCamp/vectorscan, the multi-arch version

**Comment by user959** [comment]
@hulksmaaash, thank you. I intend to do it till the end of the month

**Comment by markos** [comment]
@user959 keep in mind that we're heavily refactoring the SIMD code, and there is already a Power9 PR there for a few months already (https://github.com/VectorCamp/vectorscan/pull/20), however it was failing a couple of tests and the refactoring took precedence. We plan to merge it back once it's done, but if you have suggestions on how to improve it, they are welcome.

**Comment by Nor7th** [comment]
We only support x86 platforms officially.

**Pull request closed without merging**
