### PR TITLE
cmake: we use SSSE3, so correctly pass it to the compiler

### PR DESCRIPTION
**Pull request by okias**
Fixes failing SSSE3 test on my machine (tested on Gentoo).

Signed-off-by: David Heidelberg <david@ixit.cz>

### CODE REVIEW

**Comment by okias** [comment]
pretty please, guys?

**Comment by okias** [comment]
still need to be patched. still valid year later, why it is not merged?

**Comment by arkamar** [comment]
I don't think this is a valid solution. The purpose of the test is to detect if the CPU has necessary instructions. Your `-pipe -O2 -mtune=native` (taken from https://bugs.gentoo.org/674218) fails in following tests
https://github.com/intel/hyperscan/blob/d79973efb1fcf5ed338122882c1f896829767fb6/CMakeLists.txt#L247-L253
Therefore `-march=native` is not set before the `SSSE3` test and `-mtune` is not enough (blog-post about difference between `march` and `mtune` https://lemire.me/blog/2018/07/25/it-is-more-complicated-than-i-thought-mtune-march-in-gcc/).

Maybe we can change those tests to something like this
```cmake
    if (NOT CMAKE_C_FLAGS MATCHES .*march.*)
        set(ARCH_C_FLAGS "-march=native")
    endif()
    if (NOT CMAKE_C_FLAGS MATCHES .*mtune.*)
        set(ARCH_C_FLAGS "${ARCH_C_FLAGS} -mtune=${TUNE_FLAG}")
    endif()
```
which will work for your case, but I am not convinced it is the right solution.
Those tests are constructed in a way to be able to work properly for binary distributions, in my opinion. Even in the Gentoo we can build binary packages in our most shiny and powerful machine with all modern instructions in such a way to be able to run them in older machines where we redistribute them. And this is your setup, you are creating binaries for generic `x86_64` with performance optimization for your `native` CPU, which means without `ssse3`.

**Comment by Nor7th** [comment]
Hi @okias, the failing message of ssse3 test during cmake stage just simply means the platform does not support ssse3 execution, which is Hyperscan's minimum runtime requirement:
```
CMake Error at cmake/arch.cmake:79 (message):
  A minimum of SSSE3 compiler support is required
```
If you want to run Hyperscan on such a platform, it clearly won't work. 
If you're just using such a platform to compile Hyperscan and run it on another valid target machine (with ssse3 support), then it's a cross compile case and you can just run by: 
 ```
cmake -DCMAKE_C_FLAGS="-march=core2" \
  -DCMAKE_CXX_FLAGS="-march=core2" <hyperscan-source-path>
```
(More can be referred to http://intel.github.io/hyperscan/dev-reference/getting_started.html#target-architecture)
Whatever the case, adding `-mssse3` into CMakeLists.txt seems not to make much sense. That's our concern.

**Comment by okias** [comment]
maybe Gentoo could enforce adsing -mssse3 into

**Pull request closed without merging**
