### PR TITLE
Feature/add arm support

### PR DESCRIPTION
**Pull request by markos**
(Resubmitting the PR against 'develop' branch as suggested in #286).

This PR brings the ARM NEON port up to par with the x86. It is based on PR272 (#272), however it can be pulled in on its own as it includes the changes. All tests pass on both ARM and x86 (obviously, we wouldn't want to break x86 functionality). As already described in PR272, x86-specific code has been abstracted away and arch specific code has been put into separate headers in src/util/arch/. This way, maintining arch-specific code of hyperscan and/or porting hyperscan to a new architecture (eg Power/RISC-V/etc) should now be much easier.
Please consider merging this PR.

### CODE REVIEW

**Comment by hulksmaaash** [comment]
Unfortunately we have been informed that the project maintainers have 
> "no plan to give multi-arch support for Hyperscan" 

and will 
> "keep Hyperscan as x86 only and deliver continuous designs and optimizations based on instruction-set from current and future Intel CPUs"  

We will consider the best path forward to ensure Hyperscan will work for users who desire support for non-x86 architectures, and update those who express interest.

**Comment by markos** [comment]
It has been communicated that Intel is not interested in supporting multiple architectures in this project. Closing the PR. If interested in other architectures support, please check our fork at https://github.com/VectorCamp/hyperscan.

**Comment by a16bitsysop** [comment]
@markos I am interested in other arches, I see your fork add-arm-support is a separate branch.  Is it going to be merged into your master or is that branch the correct one for aarch64 and x86 (for building packages from)

**Comment by markos** [comment]
@a16bitsysop it's already merged in 'develop' branch on our tree.

**Comment by a16bitsysop** [comment]
@markso okay thanks, are you going to do a release tag for it.  As I would like to build an alpine linux package for it (well try and change from intel/hyperscan for alpine so can add aarch64) and to do that ideally it needs a tag (v5.3.0.1 ??). 

Or would not recommend build packages for a distribution with it just yet?

**Comment by markos** [comment]
@a16bitsysop yes, in fact I plan to release Debian packages for it soon, but let's continue the discussion there  :)

**Comment by a16bitsysop** [comment]
@markos you have issues disabled on your fork, I tried to compile but I get this error on every arch
```
hyperscan-5.3.1/unit/internal/masked_move.cpp:35:10: fatal error: util/masked_move.h: No such file or directory
943   35 | #include "util/masked_move.h"
```

I tried setting RELEASE_BUILD to on but still got the error.

**Comment by markos** [comment]
@a16bitsysop Issues are enabled now, let's continue there and I'll try to help with the build.

**Pull request closed without merging**
