### PR TITLE
Feature/split x86 dependencies

### PR DESCRIPTION
**Pull request by markos**
Hello, 
This is the first part of an ongoing effort to port hyperscan to ARM, in particular ARM NEON and Advanced SIMD support. Before we add actual ARM support, it was necessary to make the source code properly platform agnostic, with platform specific implementations in a separate folder, so that it does not make code maintainance more difficult and for aesthetic reasons (not too many ifdef ARCH in the same function).

For that reason, we did the following:
* move x86 specific types, functions and definitions to util/arch/x86 folder.
* where x86 intrinsics were used throughout the code, we replaced them with virtual intrinsics (like eg. set32x8()).
* crc32, bitutils and popcount functions were virtualized and the actual functions call the respective *_impl() functions, which can be platform-specific.
* moved cpuid specific changes to util/arch/x86.
* Minor other changes

So far, the changes made don't break compilation or performance or unit tests.
We would appreciate any feedback on this PR. 

UPDATE: popcount abstraction was reverted, the tests were failing for no apparent reason, will need to investigate.

### CODE REVIEW

**Comment by mr-c** [comment]
@markos Maybe using https://github.com/simd-everywhere/simde would help the port? It would also enable other architectures as well

**Comment by markos** [comment]
> @markos Maybe using https://github.com/simd-everywhere/simde would help the port? It would also enable other architectures as well

@mr-c This would require substantial refactoring of the internals of hyperscan, esp the algorithm implementations, more drastic than just adding NEON support, and it would also take more time. I'm not personally against it but something like that would have to be agreed by the Intel maintainers upfront. I do have a similar idea however, but I need to discuss it further.

**Comment by markos** [comment]
@mr-c for the time being, the focus is on getting NEON support in there. That does not exclude another approach in the future however.

**Comment by hulksmaaash** [comment]
@xiangwang1 Do you see any issues with this approach?

**Comment by markos** [comment]
It has been communicated that Intel is not interested in supporting multiple architectures in this project. Closing the PR. If interested in other architectures support, please check our fork at https://github.com/VectorCamp/hyperscan.

**Pull request closed without merging**
